<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Categories\Categories;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;
JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php');


// Template path
$app = Factory::getApplication();
$template   = $app->getTemplate();
$templatePath = JUri::base() . '/templates/' . $template;
$iconsPath = $templatePath . "/svg/sprites.svg";
require_once JPATH_THEMES . '/' . $template . '/functions.php';

// Create a shortcut for params.
$params  = &$this->item->params;
$canEdit = $this->item->params->get('access-edit');
$info    = $this->item->params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isUnpublished     = $this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $isNotPublishedYet || $isExpired;

$summary = findObjectValueByName($this->item->jcfields, "summary");
$intro = LayoutHelper::render('joomla.content.intro_image', $this->item);

$jcategories = Categories::getInstance('Content');
$category   = $jcategories->get($this->item->catid);
$currentCatFields = FieldsHelper::getFields('com_content.categories', $category, true);
          
$menuitemId = findObjectValueByName($currentCatFields, "menuitem-id");
          
$menu = $app->getMenu(); 
$menuitem = $menu->getItem($menuitemId);
$menuimagecss = $menuitem ? $menuitem->getParams()["menu_image_css"] : null;
$menuitemtitle = $menuitem ? $menuitem->title : null;


//var_dump($menuitem);
?>
<?php if ($isUnpublished) : ?>
		<div class="system-unpublished">
	<?php endif; ?>
        
<div class="row">
        <div class="col-lg-6 order-2 order-lg-1">
          <div class="card mb-5">
            <div class="card-body pb-5 px-0">
            
            <?php if ($params->get('show_category')) : ?>
          <div class="category-top">
          <?php if($menuimagecss !== "") {
               echo '<span class="icon fa-2x ' . $menuimagecss . '"></span>';
          }
          ?>
          
            <a class="category" href="<?php echo JRoute::_(ContentHelperRoute::getCategoryRoute($this->item->catid)) ?>"><?php echo $this->escape($this->item->category_title); ?></a>
          <?php 

    $date = new DateTime($this->item->publish_up);
          ?>
            <span class="data"><?php echo printDateFmt($date, "long"); ?></span>
          </div>
          <?php endif;?>
            
    <?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
		<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
	<?php endif; ?>
	<?php if ($isNotPublishedYet) : ?>
		<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
	<?php endif; ?>
	<?php if ($isExpired) : ?>
		<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
	<?php endif; ?>
   <?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>
            
            <?php if ($params->get('show_title')) : ?>
        <h2 class="h3 card-title" itemprop="headline">
        <?php if ($params->get('link_titles') && $params->get('access-view')) : ?>
            <a href="<?php echo Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>" class="text-decoration-none" itemprop="url">
                <?php echo $this->escape($this->item->title); ?>
            </a>
        <?php else : ?>
            <?php echo $this->escape($this->item->title); ?>
        <?php endif; ?>
        </h2>
    <?php endif; ?>
            
    <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>
    
    <?php
    
    if($summary !== "") { echo '<p class="mb-4 pt-3 lora">' . htmlspecialchars((string) $summary, ENT_QUOTES, 'UTF-8')  . '</p>'; }

    ?>
       <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
		<?php endif; ?>
            
            <?php if($menuitem) {?>
              <a class="read-more pb-3" href="<?php echo $menuitem->route; ?>">
                <span class="text">Area <?php echo htmlspecialchars((string) $menuitemtitle, ENT_QUOTES, 'UTF-8')?></span>
                <svg class="icon">
              <use xlink:href="<?php echo $iconsPath; ?>#it-arrow-right"></use>
                </svg>
              </a>
        <?php } ?>
            </div>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 px-0 px-lg-3">
          <?php echo $intro; ?>
        </div>
      </div>

	
	
	<?php if ($isUnpublished) : ?>
		</div>
	<?php endif; ?>

<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo $this->item->event->afterDisplayContent; ?>
